language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep libglib2.0-dev
# 2.47.5-5-g1426c65 requires at least libpcre >= 8.13 but version of libpcre is 8.12 (need `--enable-unicode-properties` in order to avoid `configure: error: *** The system-supplied PCRE does not support Unicode properties or UTF-8.` in `configure`)
# - wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.bz2 && tar xf pcre-8.38.tar.bz2 && cd pcre-8.38 && ./configure --enable-utf --enable-unicode-properties && make -j24 && sudo make install && cd ..
script: ./autogen.sh --enable-tests --with-pcre=internal && make -j24 && make -j24 check && sudo make install
