## Makefile for building the GLib test programs with egcs on cygwin.
## Use: make -f makefile.cygwin check

################################################################

# Nothing much configurable below

# cl -? described the options
CC = gcc -mno-cygwin -mpentium

GLIB_VER = 1.3

CFLAGS = -I.. -DHAVE_CONFIG_H

TESTS = \
	array-test.exe	\
	date-test.exe	\
	dirname-test.exe\
	hash-test.exe	\
	list-test.exe	\
	node-test.exe	\
	queue-test.exe	\
	rand-test.exe	\
	relation-test.exe\
	slist-test.exe	\
	stack-test.exe	\
	string-test.exe	\
	strfunc-test.exe\
	tree-test.exe	\
	type-test.exe

all :	$(TESTS)

.SUFFIXES: .c .exe

.c.exe :
	$(CC) $(CFLAGS) -c $<
	$(CC) $(CFLAGS) -o $@ $< -L.. -lglib-$(GLIB_VER)

check:	all
	@for P in $(TESTS) ; do echo $$P; ./$$P; done

clean:
	-rm *.exe *.o
