.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.0).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GLIB\-GETTEXTIZE" "1" "08/15/2005" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
glib\-gettextize \- gettext internationalization utility
.SH "SYNOPSIS"
.HP 16
\fBglib\-gettextize\fR [option...] [directory]
.SH "DESCRIPTION"
.PP
\fBglib\-gettextize\fR 
helps to prepare a source package for being internationalized through 
gettext. It is a variant of the 
\fBgettextize\fR 
that ships with 
gettext.
.PP
\fBglib\-gettextize\fR 
differs from 
\fBgettextize\fR 
in that it doesn't create an 
\fIintl/\fR 
subdirectory and doesn't modify 
\fIpo/ChangeLog\fR 
(note that newer versions of 
\fBgettextize\fR 
behave like this when called with the 
\fB\-\-no\-changelog\fR 
option).
.SS "Options"
.TP
\fB\-\-help\fR
print help and exit
.TP
\fB\-\-version\fR
print version information and exit
.TP
\fB\-c\fR, \fB\-\-copy\fR
copy files instead of making symlinks
.TP
\fB\-f\fR, \fB\-\-force\fR
force writing of new files even if old ones exist
.SH "SEE ALSO"
.PP
 \fBgettextize\fR(1)
