.TH "g-ir-generate" 1
.nh
.SH NAME
g-ir-generate \- typelib generator
.SH SYNOPSIS
.B g-ir-generate
[OPTION...] FILES...
.SH DESCRIPTION
g-ir-generate is an GIR generator, using the repository API. It generates
GIR files from a raw typelib or in a shared library (--shlib).
The output will be written to standard output unless the --output 
is specified.
.SH OPTIONS
.TP
.B \, --help
Show help options
.TP
.B \, --shlib=FILENAME
The shared library to read the symbols from.
.TP
.B \, --output=FILENAME
Save the resulting output in FILENAME.
.TP
.SH BUGS
Report bugs at https://gitlab.gnome.org/GNOME/gobject\-introspection/issues.
.SH HOMEPAGE and CONTACT
http://live.gnome.org/GObjectIntrospection
.SH AUTHORS
Mattias Clasen
