.TH "g-ir-compiler" 1
.nh
.SH NAME
g-ir-compiler \- typelib compiler.
.SH SYNOPSIS
.B g-ir-compiler
[OPTION...] GIRFILE
.SH DESCRIPTION
g-ir-compiler converts one or more GIR files into one or more typelib. 
The output will be written to standard output unless the --output 
is specified.
.SH OPTIONS
.TP
.B \--help
Show help options
.TP
.B \--output=FILENAME
Save the resulting output in FILENAME.
.TP
.B \--verbose
Show verbose messages
.TP
.B \--debug
Show debug messages
.TP
.B \--includedir=DIRECTORY
Adds a directory which will be used to find includes inside the GIR format.
.TP
.B \--module=MODULE
FIXME
.TP
.B \--shared-library=FILENAME
Specifies the shared library where the symbols in the typelib can be found.
The name of the library should not contain the ending shared library suffix.
.TP
.SH BUGS
Report bugs at https://gitlab.gnome.org/GNOME/gobject\-introspection/issues.
.SH HOMEPAGE and CONTACT
http://live.gnome.org/GObjectIntrospection
.SH AUTHORS
Mattias Clasen
