'\" t
.\"     Title: gobject-query
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.2 <http://docbook.sf.net/>
.\"      Date: 03/13/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "GOBJECT\-QUERY" "1" "03/13/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gobject-query \- display a tree of types
.SH "SYNOPSIS"
.HP \w'\fBgobject\-query\fR\ 'u
\fBgobject\-query\fR froots [options...]
.HP \w'\fBgobject\-query\fR\ 'u
\fBgobject\-query\fR tree [options...]
.SH "DESCRIPTION"
.PP

\fBgobject\-query\fR
is a small utility that draws a tree of types\&.
.SH "INVOCATION"
.PP

\fBgobject\-query\fR
takes a mandatory argument that specifies whether it should iterate over the fundamental types or print a type tree\&.
.SS "Options"
.PP
\fBfroots\fR
.RS 4
iterate over fundamental roots
.RE
.PP
\fBtree\fR
.RS 4
print type tree
.RE
.PP
\fB\-r\fR \fItype\fR
.RS 4
specify the root type
.RE
.PP
\fB\-n\fR
.RS 4
don\'t descend type tree
.RE
.PP
\fB\-b\fR \fIstring\fR
.RS 4
specify indent string
.RE
.PP
\fB\-i\fR \fIstring\fR
.RS 4
specify incremental indent string
.RE
.PP
\fB\-s\fR \fInumber\fR
.RS 4
specify line spacing
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print brief help and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print version and exit\&.
.RE
